package com.jobagent.jobagent.motivation.model;

/**
 * Sprint 6.1 — Status of a motivation letter.
 */
public enum LetterStatus {
    /** Initial draft, not yet generated */
    DRAFT,
    /** Generated by AI */
    GENERATED,
    /** Edited by user after generation */
    EDITED,
    /** Sent with job application */
    SENT,
    /** Archived/no longer active */
    ARCHIVED
}
